name: MatModN
version: 0.1
date: 2018-07-19
description: |
    Somewhat faster representation for matrices of integers mod n

authors:
    - name: Steve Linton
      url: http://sal.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Steve Linton
      url: http://sal.host.cs.st-andrews.ac.uk/

GAP: ">= 4.9"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.6.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://stevelinton.github.io/MatModN/
readme: README.md
packageinfo: https://stevelinton.github.io/MatModN/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/stevelinton/MatModN/releases/download/v0.1/MatModN-0.1.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Lin18</span>]   <b class='BibAuthor'>Linton, S.</b>,
     <i class='BibTitle'>MatModN, Somewhat faster representation for matrices of integers mod n,
             Version 0.1</i>
     (<span class='BibYear'>2018</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://stevelinton.github.io/MatModN/">https://stevelinton.github.io/MatModN/</a></span>.
    </p>
    

bibtex: |
    @misc{ MatModN0.1,
      author =           {Linton, S.},
      title =            {{MatModN}, Somewhat faster representation for matrices of integers mod n, {V}ersion 0.1},
      month =            {Jul},
      year =             {2018},
      note =             {GAP package},
      howpublished =     {\href             {https://stevelinton.github.io/MatModN/}            {\texttt{https://stevelinton.github.io/}\discretionary
                          {}{}{}\texttt{MatModN/}}},
      printedkey =       {Lin18}
    }

